before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HRUB3sYCwSlMeBHaeYaZiopprBtUR39AmqEuWz+kWR6vbLJcahw/BPzzsAxFET4nERiOlMDI6Ulh200FCsvXwtI7Tc9krD+6wcS6qYeFHfDjIx/06hkx5V+4k4hwsH85J3Bh49TM3gcd4pIXglXXyDLdVbfK0TC2umcg1tg7Xr89FFDgQkKs+lAZMoOZa31c0aX9DOrysW0dYnB4Johp/0amU92VV9z77FDB6I1jXorlirnAtmE+zTGUhTmnhZDpSp644C/6hUBDFCknx36I1tNXZg7VqIHmEbm7c8KTrpv5tJH24u+dwE7IzDeKIOkk9GCVrCEezBRnmLumRBrZPP7NZ64ty+s3C4TICKxiI32jumaii3rdAhns5UrUhkV8977edMXLz1N4LYEmSARCerVAZtSxCK2fdgPag2s2YNbYIOaCHwG5YBOEnsiRRlQ6fkIXBy2lSGo5CgabFlyaa4qku2BDcrVZfIKg/ZOudxhHFOwj40LxRmhNL658l4raW+fLDZEjfDtSY6hDSA7YfxW3Ostylw6iMOMqqudaLP5DDoj9uguU6jkGxX7elwc6ah39lubvsWUHjcAk5uZvs5kydIg4hO2Y9sGeuiR3CWYXMQKrp+gNVpV+sOuYrb8k22YnRPP09oVx/SZw30q0ef453B2p2mhopjVs0+omhhs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
